// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package app

// Injectors from wire.go:

func InitializeApp(cfgFile string) (*AccountApp, error) {
	v, err := ReadConfig(cfgFile)
	if err != nil {
		return nil, err
	}
	accountApp, err := NewAccountApp(v)
	if err != nil {
		return nil, err
	}
	return accountApp, nil
}
